### ISSUE TITLE
Code review for @markuslyq

### ISSUE THREAD

**Issue by stephlewyh** [AY2122S1-CS2113-T13-2/tp#154]
@markuslyq

1. This is a long method (>30LoC). How about abstracting out portions of code into methods (see [SLAP principle](https://nus-cs2113-ay2122s1.github.io/website/se-book-adapted/chapters/codeQuality.html#slap-hard))?
<img width="614" alt="Screenshot 2021-10-28 at 12 30 33 PM" src="https://user-images.githubusercontent.com/2998854/139187377-728aed09-8203-4138-970a-114497ebe482.png">

2. [Avoid repeating the obvious](https://nus-cs2113-ay2122s1.github.io/website/se-book-adapted/chapters/codeQuality.html#do-not-repeat-the-obvious) like this one:

<img width="438" alt="Screenshot 2021-10-28 at 12 33 42 PM" src="https://user-images.githubusercontent.com/2998854/139187617-b2dd0dc1-93be-4a30-a810-f3221dd85475.png">

**Comment by markuslyq** [comment]
@stephlewyh 
For point 1 it is actually two separate methods. There is actually a line skip from 78 to 92 in the image.

**Comment by markuslyq** [comment]
Resolved.
