### ISSUE TITLE
Current list of overall bugs to be addressed & their description.

### ISSUE THREAD

**Issue by andrewtkh1** [AY2122S1-CS2113-T13-2/tp#210]
Overall bugs:

Wants a more specific error message - #208, #205, #190, #188, #177
No Target Audiance, Purpose? - #207
Find command, wants to find " ". - #204
UG metions about other special requiremnts. TO be removed. - #199, #196, #184
Give more food choices in menu? - #198
Find command printing names in all small cases. - #197, #178,
Delete command error message wrong. - #195, #194, #191, #183, #167
Adding people of same name with caps inside counts as 2 different people. - #192, #187
UG delete command exapmple wrong - #189
UG Add command example out of range. - #186, #179
Inform User menu command takes no inputs. - #182
UG content page hyperlink broken - #180, #171, #166
UG to indicate command format must be followed strictly. - #174
UG to indicate file is not saved. - #173
Update UG menu photo. - #172
Edit to 0 order to inform deleted. - #170
Spelling in UG ("Quantity") - #169
Gliches in command?? - #181

**Comment by andrewtkh1** [comment]
Solutions:
Specific error message - To tell users to check values & format in UG.
No Target Audiance, Purpose? - YZ doing
*CONVERT ALL NAME TO UPPER CASE

**Comment by WaiKit-nus** [comment]
#208, #205, #190, #188, #177,  #197, #178,  #192, #187- WK
#207,  #198,  #172, #170, #169 - YZ
#199, #196, #184, #182, #186, #179, #182, #174 - Adam
#195, #194, #191, #183, #167, #189 - Markus
#204, #180, #171, #166 - Andrew (Solution: Add the comment in UG)
